---
# Date: 2025-06-01
# https://hub.docker.com/r/linuxserver/jellyfin
# https://jellyfin.org/docs/
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=<TODO user UID>
      - PGID=<TODO group GID>
      - TZ=<TODO timezone ex. America/Chicago>
      #- JELLYFIN_PublishedServerUrl=192.168.10.108 #optional
    volumes:
      - /<TODO dockerappconfig path>/jellyfin/library:/config
      - /<TODO dockerdata path>/media/music:/data/music
      - /<TODO dockerdata path>/media/movies:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
